import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner/banner'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1> Creating NetFlix clone</h1>
      {/*   <Navbar /> */}

      <Banner 
      title="How to train your dragon" 
      subtitle=" very cute dragons"
      imgUrl="/static/bannerImage.webp" />
    </div>
  );
}

export default Home
